import 'package:ag_smart/View%20Model/database/cache_helpher.dart';

String chosenLanguage = CacheHelper.getData(key: 'language') ?? '';
String stationName = CacheHelper.getData(key: 'stationName') ?? '';
int numOfActiveLines = CacheHelper.getData(key: 'numOfActiveLines') ?? 0;
int stationId = CacheHelper.getData(key: 'stationId') ?? 0;
String token = CacheHelper.getData(key: 'token') ?? '';
String refreshToken = CacheHelper.getData(key: 'refreshToken') ?? "";
int userId = CacheHelper.getData(key: 'user_id') ?? 0;
String serialNumber = CacheHelper.getData(key: 'serialNumber') ?? "";
bool isLanguageChosen = CacheHelper.getData(key: 'languageChoosen') ?? false;
int binaryValves = CacheHelper.getData(key: 'binaryValves') ?? 0;

Map<String, Map<String, String>> text = {
  'en': {
    'sign in name': 'Username',
    'Password': 'Password',
    'Sign in': 'Sign in',
    'confirm password': 'Confirm Password',
    'Create account': 'Create account',
    'Create a new account': 'Create a new account',
    'Change network name': 'Change network name',
    'Horse': 'Horse',
    'Nothing': 'Nothing',
    'Diameter': 'Diameter',
    'Number': 'Number',
    'Series Irrigation': 'Series Irrigation',
    'Manual Irrigation': 'Manual Irrigation',
    'Parallel Irrigation': 'Parallel Irrigation',
    'Custom Irrigation': 'Custom Irrigation',
    'Automatic Irrigation': 'Automatic Irrigation',
    'Irregular water pressure': 'Irregular\nwater\npressure',
    'According to cycle': 'According to cycle',
    'According to time': 'According to time',
    'Watering duration': 'Watering duration',
    'According to quantity': 'According to quantity',
    'Fertilizer': 'Fertilizer',
    'Fertilizer Settings': 'Fertilizer Settings',
    'Scarecrow': 'Scarecrow',
    'Scarecrow Settings': 'Scarecrow Settings',
    'Light': 'Light',
    'Light Settings': 'Light Settings',
    'Settings': 'Settings',
    'Set time': 'Set time',
    'Open valve time': 'Open valve time',
    'Add a period': 'Add a period',
    'Remove a period': 'Remove a period',
    'Device Features': 'Device Features',
    'Lines\' Settings': 'Lines\' Settings',
    'Lines Activation': 'Lines Activation',
    'Line Settings': 'Line Settings',
    'Pump Settings': 'Pump Settings',
    'Irrigation type': 'Irrigation type',
    'Duration settings': 'Duration settings',
    'Duration': 'Duration',
    'Each cycle': 'Each cycle',
    'Set day': 'Set day',
    'Set date': 'Set date',
    'From': 'From',
    'To': 'To',
    'Turn on': 'Turn on',
    'Turn off': 'Turn off',
    'Hours': 'Hours',
    'Minutes': 'Minutes',
    'ml': 'ml',
    'Amount of water': 'Amount of water',
    'Lighting time': 'Lighting time',
    'Fertillization amount': 'Fertillizer amount',
    'Back to home page': 'Back to home page',
    'Device Setup': 'Device Setup',
    'Station info': 'Station info',
    'Station name': 'Station name',
    'Contact us': 'Contact us',
    'About us': 'About us',
    'Change language': 'Change language',
    'Log out': 'Log out',
    'Sure': 'Are you sure?',
    'Yes': 'Yes',
    'No': 'No',
    'Auto duration': 'Auto duration',
    'Irrigation Settings': 'Irrigation Settings',
    'Fertilization Settings': 'Fertilization Settings',
    'Fertilizing by duration': 'Fertilizing by duration',
    'Fertilizing by quantity': 'Fertilizing by quantity',
    'Series Fertilization': 'Series Fertilization',
    'Parallel Fertilization': 'Parallel Fertilization',
    'line': 'line',
    'Next': 'Next',
    'You are not subscribed for this feature':
        'You are not subscribed for this feature',
    'Dashboard': 'Dashboard',
    '[ + ] Add device': '[ + ] Add device',
    'Water consumption (Liter)': 'Water consumption (Liter)',
    'Report': 'Report',
  },
  'ar': {
    'sign in name': 'اسم المستخدم',
    'Password': 'كلمة المرور',
    'Sign in': 'تسجيل الدخول',
    'Create account': 'انشاء الحساب',
    'confirm password': 'تأكيد كلمة المرور',
    'Create a new account': 'انشاء حساب جديد',
    'Change network name': 'تغيير اسم المستخدم',
    'Horse': 'حصان',
    'Nothing': 'لا يوجد',
    'Diameter': 'قطر',
    'Number': 'عدد',
    'Series Irrigation': 'الري بالتوالي',
    'Manual Irrigation': 'الري اليدوي',
    'Parallel Irrigation': 'الري بالتوازي',
    'Custom Irrigation': 'الري المخصص',
    'Automatic Irrigation': 'الري الأوتوماتيكي',
    'Irregular water pressure': 'ضغط ماء\n غير منتظم',
    'According to cycle': 'ري حسب الدورة',
    'According to time': 'حسب الساعة',
    'Watering duration': 'مدة الري',
    'According to quantity': 'حسب الكمية',
    'Fertilizer': 'تسميد',
    'Fertilizer Settings': 'إعدادات التسميد',
    'Scarecrow': 'الفزاعة',
    'Scarecrow Settings': 'إعدادات الفزاعة',
    'Light': 'الإضاءة',
    'Light Settings': 'إعدادات الضوء',
    'Settings': 'الإعدادات',
    'Set time': 'تحديد الساعة',
    'Open valve time': 'مدة فتح الصمام',
    'Add a period': 'إضافة فترة',
    'Remove a period': 'ازالة فترة',
    'Device Features': 'ميزات الجهاز',
    'Lines\' Settings': 'إعدادات الخطوط',
    'Line Settings': 'إعدادات الخط',
    'Lines Activation': 'تفعيل الخطوط',
    'Pump Settings': 'إعدادات المضخة',
    'Irrigation type': 'نوع الري',
    'Duration settings': 'إعدادات المدة',
    'Duration': 'المدة',
    'Each cycle': 'كل دورة ري',
    'Set day': 'تحديد اليوم',
    'Set date': 'تحديد التاريخ',
    'From': 'من',
    'To': 'إلي',
    'Turn on': 'تشغيل',
    'Turn off': 'ايقاف',
    'Hours': 'ساعة',
    'Minutes': 'دقيقة',
    'ml': 'مل',
    'Amount of water': 'كمية الماء',
    'Lighting time': 'مدة الإضاءة',
    'Fertillization amount': 'كمية التسميد',
    'Back to home page': 'العودة للصفحة الرئيسية',
    'Device Setup': 'إعداد الجهاز',
    'Station info': 'معلومات المحطة',
    'Contact us': 'اتصل بنا',
    'About us': 'معلومات عنا',
    'Change language': 'تغيير اللغة',
    'Log out': 'تسجيل الخروج',
    'Sure': 'هل أنت واثق؟',
    'Yes': 'نعم',
    'No': 'لا',
    'Auto duration': 'مدة أوتوماتيكية',
    'Irrigation Settings': 'اعدادات الري',
    'Fertilization Settings': 'اعدادات التسميد',
    'Fertilization by duration': 'تسميد حسب الساعة',
    'Fertilization by quantity': 'تسميد حسب الكمية',
    'Series Fertilization': 'تسميد بالتوالي',
    'Parallel Fertilization': 'تسميد بالتوازي',
    'Fertilizing by duration': 'التسميد بالمدة',
    'Fertilizing by quantity': 'التسميد بالكمية',
    'Station name': 'اسم المحطة',
    'line': 'خط',
    'Next': 'التالي',
    'You are not subscribed for this feature': 'لست مشترك في هذه الخدمة',
    'Dashboard': 'الصفحة الرئيسية',
    '[ + ] Add device': 'إضافة جهاز [ + ]',
    'Water consumption (Liter)': 'إستهلاك الماء (لتر)',
    'Report': 'تقرير',
  },
};
